### ISSUE TITLE
Is diff_graph() an implementation of the U-matrix?

### ISSUE THREAD

**Issue by rohitgavval** [fcomitani/simpsom#2]
Hi Federico,

I looked into the code and the only difference between the U-matrix and your implementation of diff_graph() seems to be that the former takes an average of the distances with its neighbours while diff_graph() just takes the sum. Is diff_graph() an implementation of the U-matrix?

**Comment by fcomitani** [comment]
Hello Rohit, 

apologies for the late reply.

I believe the original definition of U-matrix requires to add extra "padding" nodes between each pair of nodes colored according to the distance of the neighbors.

This definition is used in [SOM Toolbox](http://www.cis.hut.fi/somtoolbox/package/docs2/som_umat.html) (a Matlab package for SOM).

>  Compute and return the unified distance matrix of a SOM. 
>  For example a case of 5x1 -sized map:
>             m(1) m(2) m(3) m(4) m(5)
>  where m(i) denotes one map unit. The u-matrix is a 9x1 vector:
>     u(1) u(1,2) u(2) u(2,3) u(3) u(3,4) u(4) u(4,5) u(5) 
>  where u(i,j) is the distance between map units m(i) and m(j) and u(k) is the mean (or minimum, maximum or median) of the surrounding values, e.g. u(3) = (u(2,3) + u(3,4))/2.  

The implementation of diff_graph() is more similar to an alternative, simplified representation of the U-matrix that can be found in some works (see this [paper](https://www.uni-marburg.de/fb12/arbeitsgruppen/datenbionik/pdf/pubs/2003/ultsch03ustar)).

> The U-Matrix is constructed on top of the map. 
> Let n be a neuron on the map, NN(n) be the set of immediate neighbors on the map, w(n) the weight vector associated with neuron n, then  
> 
> U-height(n) = SUM( for m ∈ NN(n)) d(w(n)-w(m)), where d(x,y) is the distance used in the SOM algorithm to construct  the  map.  
> 
> The  U-Matrix  is  a  display  of  the  U-heights  on  top  of  the  grid  positions  of  the  
> neurons on the map.

The actual difference (except for a scaling factor which is fixed and dependent on the geometry of the map) boils down to the interpolating nodes. I personally prefer the second implementation because the resulting map is more intuitive for me, it's easier to read and compare with the other maps produced.

 There seems to be a scarcity of information on this argument online, but there are a few discussions (like [this one](https://stackoverflow.com/questions/13631673/how-do-i-make-a-u-matrix)) on stack overflow if you are interested in more details.

**Comment by fcomitani** [comment]
Hello Rohit,

if there are no further question I'm going to close this issue.
